server:
  port: 8000
  secretkey: SECRET_KEY
  Environment: "development"
  cors_allowed_origins:
  - "*"

db:
  host: go_db
  port: 5432
  user: postgres
  password: 1234
  dbname: postgres
  sslmode: disable
  timezone: saopaolo