// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/google/wire"
	"go-api/internal/adapter/http/controller"
	"go-api/internal/adapter/repository"
	"go-api/internal/adapter/repository/postgres"
	"go-api/internal/core/usecase"
)

// Injectors from injector.go:

func Init() *Initialization {
	db := postgres.Connect()
	userRepositoryImpl := postgres.NewUserRepository(db)
	productRepositoryImpl := postgres.NewProductRepository(db)
	userUsecaseImpl := usecase.NewUserUsecase(userRepositoryImpl)
	productUsecaseImpl := usecase.NewProductUsecase(productRepositoryImpl)
	loginControllerImpl := controller.NewLoginController(userUsecaseImpl)
	userControllerImpl := controller.NewUserController(userUsecaseImpl)
	productControllerImpl := controller.NewProductController(productUsecaseImpl)
	initialization := NewInitialization(userRepositoryImpl, productRepositoryImpl, userUsecaseImpl, productUsecaseImpl, loginControllerImpl, userControllerImpl, productControllerImpl)
	return initialization
}

// injector.go:

var pqconn = wire.NewSet(postgres.Connect)

var userRepositorySet = wire.NewSet(postgres.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*postgres.UserRepositoryImpl)))

var productRepositorySet = wire.NewSet(postgres.NewProductRepository, wire.Bind(new(repository.ProductRepository), new(*postgres.ProductRepositoryImpl)))

var userUsecaseSet = wire.NewSet(usecase.NewUserUsecase, wire.Bind(new(usecase.UserUsecase), new(*usecase.UserUsecaseImpl)))

var productUsecaseSet = wire.NewSet(usecase.NewProductUsecase, wire.Bind(new(usecase.ProductUsecase), new(*usecase.ProductUsecaseImpl)))

var loginControllerSet = wire.NewSet(controller.NewLoginController, wire.Bind(new(controller.LoginController), new(*controller.LoginControllerImpl)))

var userControllerSet = wire.NewSet(controller.NewUserController, wire.Bind(new(controller.UserController), new(*controller.UserControllerImpl)))

var productControllerSet = wire.NewSet(controller.NewProductController, wire.Bind(new(controller.ProductController), new(*controller.ProductControllerImpl)))
